### ISSUE TITLE
Add compatibility to ePIC DTR

### ISSUE THREAD

**Issue by maximiliani** [maximiliani/idoris#7]
- [ ] Import PID-InfoTypes and PID-BasicInfoTypes as Data Types
- [ ] Import Kernel Information Profiles and Typed Information Profiles as Type Profiles
- [ ] Provide legacy endpoint which displays information from IDORIS in the same format as the "old" DTR (for compatibility reasons)
- [ ] Add update feature to automatically compare IDORIS version to DTR version of things
